import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const playfair = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "700", "500", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.className} bg-slate-950`}>{children}</body>
    </html>
  );
}
